// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDR3Fy81xWDQf7QpnKXm4mmBq9nglroog',
    appId: '1:562532198002:web:fcefe9271894b3638bc4eb',
    messagingSenderId: '562532198002',
    projectId: 'hotel-guide-2c63d',
    authDomain: 'hotel-guide-2c63d.firebaseapp.com',
    storageBucket: 'hotel-guide-2c63d.appspot.com',
    measurementId: 'G-MLR8Y7KF1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlj3087Z9VmWRYVKzzd60QSfKkSXCHXks',
    appId: '1:562532198002:android:34e39f0984acecd28bc4eb',
    messagingSenderId: '562532198002',
    projectId: 'hotel-guide-2c63d',
    storageBucket: 'hotel-guide-2c63d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_51cDcVffiW2smjs3e3a3w9Nb38JsN_M',
    appId: '1:562532198002:ios:2f7ca04a5a451c4d8bc4eb',
    messagingSenderId: '562532198002',
    projectId: 'hotel-guide-2c63d',
    storageBucket: 'hotel-guide-2c63d.appspot.com',
    iosBundleId: 'com.example.hotelGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_51cDcVffiW2smjs3e3a3w9Nb38JsN_M',
    appId: '1:562532198002:ios:d46a5f50651e02f08bc4eb',
    messagingSenderId: '562532198002',
    projectId: 'hotel-guide-2c63d',
    storageBucket: 'hotel-guide-2c63d.appspot.com',
    iosBundleId: 'com.example.hotelGuide.RunnerTests',
  );
}
